name: E2E

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: get node-version
      id: node-version-backend
      uses: juliangruber/read-file-action@v1
      with:
        path: './backend/.node-version'
        trim: true

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.node-version-backend.outputs.content }}'
        cache: 'yarn'
        cache-dependency-path: './backend/yarn.lock'

    - name: run yarn install
      run: yarn --frozen-lockfile --non-interactive
      working-directory: './backend'

    - name: run backend
      run: |
        yarn dev > /dev/null 2>&1 &
      working-directory: './backend'

    - name: get node-version
      id: node-version-frontend
      uses: juliangruber/read-file-action@v1
      with:
        path: ./frontend/.node-version
        trim: true

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.node-version-frontend.outputs.content }}'
        cache: 'yarn'
        cache-dependency-path: './frontend/yarn.lock'

    - name: run yarn install
      run: yarn --frozen-lockfile --non-interactive
      working-directory: './frontend'

    - name: run frontend
      run:  |
        yarn dev > /dev/null 2>&1 &
      working-directory: './frontend'

    - name: yarn install e2e
      run: yarn --frozen-lockfile --non-interactive
      working-directory: './e2e'

    - name: browser install
      run: yarn playwright install
      working-directory: './e2e'

    - name: run e2e
      run: node exec_e2e.js
      working-directory: './e2e'

