name: E2E

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: get node-version
      id: node-version
      uses: juliangruber/read-file-action@v1
      with:
        path: './backend/.node-version'
        trim: true

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.node-version.outputs.content }}'
        cache: 'yarn'
        cache-dependency-path: './backend/yarn.lock'

    - name: run yarn install
      run: yarn --frozen-lockfile --non-interactive
      working-directory: './backend'

    - name: run backend
      run: |
        yarn dev > /dev/null 2>&1 &
        curl http://localhost:4000
      working-directory: './backend'

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: get node-version
      id: node-version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./frontend/.node-version
        trim: true

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.node-version.outputs.content }}'
        cache: 'yarn'
        cache-dependency-path: './frontend/yarn.lock'

    - name: run yarn install
      run: yarn --frozen-lockfile --non-interactive
      working-directory: './frontend'

    - name: run frontend
      run:  |
        yarn dev > /dev/null 2>&1 &
        curl http://localhost:4001
      working-directory: './frontend'
